---
- name: Install hotspot and DHCP server.
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - isc-dhcp-server
    - hostapd
    - dnsmasq 

# If you are not using the RTL8188CUS chipset in your Wi-Fi adapter, comment
# out the following three lines.  
- name: Workaround for IP address not persisting across reboots.
  copy: src=hostapd dest=/usr/sbin/hostapd
  sudo: yes

- name: Copy the new DHCP configurations into place.
  copy: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  sudo: yes

- name: Tell DHCP server which interface to use.
  copy: src=isc-dhcp-server dest=/etc/default/isc-dhcp-server
  sudo: yes

- name: Update network interface configurations.
  copy: src=interfaces dest=/etc/network/interfaces
  sudo: yes

- name: Redirect 80 to 3000
  copy: src=iptables.conf dest=/etc/network/iptables
  sudo: yes

- name: Assign static IP address to wireless interface.
  shell: ifconfig wlan0 192.168.42.1
  sudo: yes

- name: Move the hostapd file into place.
  copy: src=hostapd.conf dest=/etc/hostapd/hostapd.conf
  sudo: yes

- name: Input our chosen Radio chipset into the hostapd config file.
  lineinfile: dest=/etc/hostapd/hostapd.conf  regexp=^'driver=' line='driver={{ chipset }}'
  sudo: yes

- name: Input our chosen SSID into the hostapd config file.
  lineinfile: dest=/etc/hostapd/hostapd.conf  regexp=^'ssid=' line='ssid={{ ssid }}'
  sudo: yes

- name: Point hostapd at the configurations file.
  lineinfile: dest=/etc/default/hostapd  regexp=^'DAEMON_CONF=""' line='DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  sudo: yes

- name: Do dnsmasq conf
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf
  sudo: yes

- name: Restart dnsmasq
  service: name=dnsmasq state=restarted
  sudo: yes

- name: Turn off dnsmasq when an ethernet cable is plugged in
  lineinfile: "dest=/etc/ifplugd/ifplugd.action line='\tservice dnsmasq stop' insertafter='^up' state=present"
  sudo: yes

- name: Turn on dnsmasq when an ethernet cable is unplugged 
  lineinfile: "dest=/etc/ifplugd/ifplugd.action line='\tservice dnsmasq start' insertafter='^down' state=present"
  sudo: yes

- name: Get Nodejs
  get_url: url="http://node-arm.herokuapp.com/node_latest_armhf.deb" dest=/home/pi/node.deb mode=0755
  sudo: yes

- name: install Nodejs
  apt: deb=/home/pi/node.deb
  sudo: yes

- name: Install global npm modules 
  npm: name={{ item }} state=latest global=yes
  sudo: yes
  with_items:
    - forever 
    - bower 
    - gulp 
  
- name: Install liblib npm module
  npm: name=liblib path=/home/pi state=latest

- name: Start liblib now
  shell: forever start /home/pi/node_modules/liblib/liblibd/index.js

- name: move ifplugd  configurations into place
  copy: src=ifplugd dest=/etc/default/ifplugd
  sudo: yes

- name: Make  hostapdstart at boot.
  shell: update-rc.d hostapd enable
  sudo: yes

- name: Make isc-dhcp-server start at boot.
  shell: update-rc.d isc-dhcp-server enable
  sudo: yes

- name: Run liblib at startup
  lineinfile: dest=/etc/rc.local line="su pi -c 'forever start --uid liblibd -a /home/pi/node_modules/liblib/liblibd/index.js < /dev/null &'" regexp='^.*liblib.*$' insertbefore="^exit" state=present
